-- Migration generated for sample_data table

CREATE TABLE IF NOT EXISTS public.sample_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT,
    description TEXT,
    user_id UUID REFERENCES auth.users(id)
);

-- Enable Row Level Security
ALTER TABLE public.sample_data ENABLE ROW LEVEL SECURITY;

-- Create Policies
CREATE POLICY "Users can view their own sample data" 
ON public.sample_data 
FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own sample data" 
ON public.sample_data 
FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own sample data" 
ON public.sample_data 
FOR UPDATE 
USING (auth.uid() = user_id);
